<?php 
$cat =  wo_categories();
   $user_id=$wo['user']['user_id'];
 $get_categories_user =  get_categories_user($user_id);
foreach ($get_categories_user as $key => $value) {
$categories = $value['categories'];		
 }
$data2 = explode(",", $categories);
 //print_r($data2);
 ?>

<style type="text/css">
   .radio-btn li{
      color: #AAAAAA;
      display: block;
      position: relative;
      float: left;
      width: 100%;
      height: 80px;
      border-bottom: 1px solid #333;
      }
      .radio-btn li input[type=radio]{
      position: absolute;
      visibility: hidden;
      }
      .radio-btn li label{
      display: block;
      position: relative;
      font-weight: 300;
      font-size: 20px ;
      padding: 20px 25px 25px 58px;
      margin: 10px auto;
      height: 30px;
      z-index: 9;
      text-align: left;
      color: #000;
      font-weight: bold;
      cursor: pointer;
      -webkit-transition: all 0.25s linear;
      }
      .radio-btn li .check{
      display: block;
      position: absolute;
      border: 1px solid #e2e2e2;
      border-radius: 100%;
      height: 25px;
      width: 25px;
      top: 30px;
      left: 20px;
      z-index: 5;
      transition: border .25s linear;
      -webkit-transition: border .25s linear;
      }
      .radio-btn li:hover .check {
      border: 1px solid #e2e2e2;
      }
      .radio-btn li .check::before {
      display: block;
      position: absolute;
      content: '';
      border-radius: 100%;
      height: 15px;
      width: 15px;
      top: 4px;
      left: 0px;
      right: 0;
      margin: auto;
      transition: background 0.25s linear;
      -webkit-transition: background 0.25s linear;
      }
      .radio-btn input[type=radio]:checked ~ .check {
      border: 1px solid #e2e2e2;
      }
      .radio-btn input[type=radio]:checked ~ .check::before{
      background: #333333;
      }
      .radio-btn input[type=radio]:checked ~ label{
      color: #000;
      }
      .login-form{
      display: flex;
      justify-content: center;
      align-items: center;
      justify-content: center;
      height: 100vh;
      width: 100%;
      text-align: center;
      }
      #regForm{
      position:relative;
      box-shadow: 1px 2px 3px 2px rgba(0, 0, 0, 0.1) !important;
      }
      btn{
      outline:none;
      }
      .right{
      background-color:rgba(0,0,0,0.7);
     background-image: url('images/2.png');
      background-repeat: no-repeat;
      background-position: center;
      background-size: contain;
     
      }
      .check-image-span{
      top: 0;
      position: absolute;
      left: 0;
      right: 0;
      width: 100%;
      height: 100%;
      }
      .check-image {
      position: relative;
      }	
.wo_settings_page{
	width: 100%;
    float: left;
}
.form-horizontal{
	    width: 100%;
    float: left;
    overflow-y: scroll;
        overflow-x: hidden;
    height: 300px;
    text-align:center;
}
.check-image p{

}
</style>
 <div class="wo_settings_page">
	<h3><?php echo $wo['lang']['categories']; ?></h3>

	<form  method="post" class="form-horizontal setting-profile-form" id="get_cat" accept-charset="UTF-8" class="add-categories">
		
         <div class="row">
		
         <?php 
	foreach ($cat as $key => $value) {
     $value['id'];
     $value['title'];
     $value['image'];?>
      
     <div class="col-md-4"><label class="btn check-image ">
       <img width="45px" src="<?php echo  $wo['config']['site_url'];?>/upload/<?php echo $value['image'];?>" alt="..." class=" img-check">
       <input type="checkbox"   name="chk2[]" id="item4" value="val2" class="hidden" autocomplete="off">
      <span class="check-image-span check-image-span1"></span>
      </label> 
      <p><?php  echo $value['title'];?></p>
      </div>
<?php } ?>
</div>
      
		
         
         

        
   </form>
</div>
<script>
        $(document).ready(function(){
    var $checkboxes = $('#get_cat  input[type="checkbox"]');  
    $checkboxes.change(function(){
        //  $('#nextBtn').prop('disabled', true);   
        var countCheckedCheckboxes = $checkboxes.filter(':checked').length;
        if(countCheckedCheckboxes < 5)
        {
          $('#submit').prop('disabled', true);  
            $("#submit").css("background-color", "#ccc");
             $("#submit").css("color", "#000");
        }
        else
        {
           $('#submit').prop('disabled', false); 
           $("#submit").css("background-color", "#e60120"); 
           $("#submit").css("color", "#fff");
           $("#nextBtn").hide();
           $("#submit").show();
        }
        //alert(countCheckedCheckboxes);
        
        
    });

});
      </script>
       <script>
         $(document).ready(function(e){
                $(".check-image-span").click(function(){
                $(this).toggleClass("right");
              });
          });
      </script>